name: Deploy WordPress via FTP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to server via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local-dir: ./
          server-dir: "/home/lpmindu1/public_html/lpmindustria/"
          exclude: |
            **/.git*     
            **/.git*/**   
            **/.github*/**
            **/wp-content/uploads/**
            **/wp-content/cache/**
            **/node_modules/**
            **/vendor/**
            .env
            .htaccess
          dangerous-clean-slate: false
          log-level: verbose
          timeout: 300000
